### ISSUE TITLE
No module named usb1

### ISSUE THREAD

**Issue by johnjelinek** [ynsta/steamcontroller#18]
```
pi@raspberry:~/Documents/steamcontroller/scripts $ sudo ./sc-dump.py 
Traceback (most recent call last):
  File "./sc-dump.py", line 28, in <module>
    from steamcontroller import SteamController
  File "/usr/local/lib/python2.7/dist-packages/steamcontroller/__init__.py", line 21, in <module>
    import usb1
ImportError: No module named usb1
```

None of the scripts run for me.
```
pi@raspberry:~/Documents/steamcontroller/scripts $ lsusb -d 28de:1142Bus 001 Device 006: ID 28de:1142 
```

**Comment by johnjelinek** [comment]
I did `pip install libusb1` now the next error:
```
pi@raspberry:~/Documents/steamcontroller/scripts $ sudo ./sc-dump.py 
Traceback (most recent call last):
  File "./sc-dump.py", line 28, in <module>
    from steamcontroller import SteamController
  File "/usr/local/lib/python2.7/dist-packages/steamcontroller/__init__.py", line 24, in <module>
    from enum import IntEnum
ImportError: cannot import name IntEnum
```

**Comment by johnjelinek** [comment]
had to `pip install enum34`
