### ISSUE TITLE
sc-xbox and sc-desktop don't seem to do anything

### ISSUE THREAD

**Issue by parkerlreed** [ynsta/steamcontroller#4]
Arch x86_64
steam 1.0.0.50-2
steamcontroller-udev 1.0-2
python-steamcontroller-git 074ccf2-1

User is in the steam group. sc-dump lists info coming from the controller.

Starting Steam the mouse/scrolling works. I've noticed that when I launch a game through Big Picture (tried Race the Sun) it doesn't show up as a controller at all. I then exited steam and tried sc-xbox/desktop. They don't error out but the controller doesn't seem to do anything in either mode. This controller did have a firmware update in Windows if that makes a difference.

**Comment by parkerlreed** [comment]
Ok weird. Even though I had the udev file installed and I was in the right group I had to use sudo to get xbox and desktop working. dump and plot both worked as normal user.

**Comment by Drakulix** [comment]
I had the same error and it turned out, I had no write permissions on uinput. You might wanna try to run the driver with sudo to check, if its a permission problem.

**Comment by ynsta** [comment]
Is the udev rules installed with your user in the group set in the udev rules ?

If you use my udev rules verify that your user is un `games` group.

`gpasswd --add $USER games`

To debug sc-xbox.py use debug instead of start. Start is in daemon mode so there is no output. 

In daemon mode error should still be logged in your journal:
`journalctl $(which sc-desktop.py)`

**Comment by ynsta** [comment]
I plan to improve the documentation on the subject.

**Comment by parkerlreed** [comment]
Thanks that is working now. I have both the steam and steamcontroller-udev udev files with my user in the "games" group and everything is working.

**Comment by DanielJoyce** [comment]
Same issue, I added my user to the games group, logged out, logged back in and it won't work. If I set GROUP="my-primary-group" in the rules, it works.

**Comment by Silent-Hunter** [comment]
I am having the same issue, but I'm in all the groups in question.

I am using the latest version of 'steamcontroller', I just cloned it today.

I have tried several .rules files, the first being:
# Valve USB devices
SUBSYSTEM=="usb", ATTRS{idVendor}=="28de", MODE="0666"
# Steam Controller udev write access
KERNEL=="uinput", SUBSYSTEM=="misc", MODE="0660", GROUP="input"
# HTC Vive HID Sensor naming and permissioning
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0bb4", ATTRS{idProduct}=="2c87", MODE="0666"

The one above gets me haptics but no controls.

Next I tried the one you posted verbatim, as I am in the games group but that one does nothing at all.

I then tried having both in separate rules files, but that did the same thing as having the first one. I don't know what static_node=uinput does, but the Gentoo rules file doesn't include that.

sc-dump.py works, and the controller works nicely in Steam, but I can't get it to work in dolphin-emu, which doesn't see the controller as an evdev device.

**Comment by Silent-Hunter** [comment]
Pardon the mess, Markdown grabbed it.

**Comment by Silent-Hunter** [comment]
AAAAAAHHH I'm an idiot! I forgot to enable uinput when I compiled my kernel. Oh my GOD this is why I've been having so many problems with xboxdrv and everything.

Sorry to bother you!

**Comment by Kokokokoka** [comment]
Can't get steam controller working. I'm using a wired connection. My user is in the games group, the rules in the readme are added, debug output:
on connect udevadm `KERNEL[1351.335795] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1 (usb)
KERNEL[1351.341715] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0 (usb)
KERNEL[1351.347877] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013 (hid)
KERNEL[1351.348167] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35 (input)
KERNEL[1351.403577] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/event8 (input)
KERNEL[1351.403616] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::numlock (leds)
KERNEL[1351.403642] change   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::numlock (leds)
KERNEL[1351.403663] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::capslock (leds)
KERNEL[1351.403686] change   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::capslock (leds)
KERNEL[1351.403705] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::scrolllock (leds)
KERNEL[1351.403725] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::compose (leds)
KERNEL[1351.403744] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::kana (leds)
KERNEL[1351.403768] change   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::kana (leds)
KERNEL[1351.404525] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/hidraw/hidraw3 (hidraw)
KERNEL[1351.406693] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1 (usb)
KERNEL[1351.412869] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014 (hid)
KERNEL[1351.415926] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36 (input)
KERNEL[1351.415967] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36/event9 (input)
KERNEL[1351.415995] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36/mouse0 (input)
KERNEL[1351.416022] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/hidraw/hidraw4 (hidraw)
KERNEL[1351.418583] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2 (usb)
KERNEL[1351.424741] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2/0003:28DE:1102.0015 (hid)
KERNEL[1351.430237] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2/usbmisc/hiddev1 (usbmisc)
KERNEL[1351.430290] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2/0003:28DE:1102.0015/hidraw/hidraw5 (hidraw)
UDEV  [1351.948764] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1 (usb)
UDEV  [1351.950214] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0 (usb)
UDEV  [1351.950304] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1 (usb)
UDEV  [1351.951128] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013 (hid)
UDEV  [1351.951420] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2 (usb)
UDEV  [1351.952142] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/hidraw/hidraw3 (hidraw)
UDEV  [1351.952699] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35 (input)
UDEV  [1351.952964] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014 (hid)
UDEV  [1351.953175] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2/usbmisc/hiddev1 (usbmisc)
UDEV  [1351.953714] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::numlock (leds)
UDEV  [1351.954022] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2/0003:28DE:1102.0015 (hid)
UDEV  [1351.954719] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2/0003:28DE:1102.0015/hidraw/hidraw5 (hidraw)
UDEV  [1351.955003] change   /devices/pci0000:00/0000:00:04..0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::numlock (leds)
UDEV  [1351.955238] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::scrolllock (leds)
UDEV  [1351.955835] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::kana (leds)
UDEV  [1351.956018] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36 (input)
UDEV  [1351.956127] change   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::kana (leds)
UDEV  [1351.957203] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::capslock (leds)
UDEV  [1351.957500] change   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::capslock (leds)
UDEV  [1351.957679] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36/mouse0 (input)
UDEV  [1351.958284] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::compose (leds)
UDEV  [1351.958843] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/hidraw/hidraw4 (hidraw)
UDEV  [1351.983821] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/event8 (input)
UDEV  [1352.060067] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36/event9 (input)
`
after the debug command:
`UDEV  [1352.060067] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36/event9 (input)
.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::numlock (leds)
UDEV  [1351.955238] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::scrolllock (leds)
UDEV  [1351.955835] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::kana (leds)
UDEV  [1351.956018] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36 (input)
UDEV  [1351.956127] change   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::kana (leds)
UDEV  [1351.957203] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::capslock (leds)
UDEV  [1351.957500] change   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::capslock (leds)
UDEV  [1351.957679] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36/mouse0 (input)
UDEV  [1351.958284] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::compose (leds)
UDEV  [1351.958843] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/hidraw/hidraw4 (hidraw)
UDEV  [1351.983821] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/event8 (input)
UDEV  [1352.060067] add      /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36/event9 (input)
KERNEL[1483.204381] add      /devices/virtual/input/input37 (input)
KERNEL[1483.204485] add      /devices/virtual/input/input37/event16 (input)
UDEV  [1483.206232] add      /devices/virtual/input/input37 (input)
UDEV  [1483.217281] add      /devices/virtual/input/input37/event16 (input)
KERNEL[1483.240109] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/event8 (input)
UDEV  [1483.240762] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/event8 (input)
KERNEL[1483.253363] change   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::numlock (leds)
KERNEL[1483.253387] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::numlock (leds)
KERNEL[1483.253409] change   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::capslock (leds)
KERNEL[1483.253426] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::capslock (leds)
KERNEL[1483.253443] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::scrolllock (leds)
KERNEL[1483.253459] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::compose (leds)
KERNEL[1483.253479] change   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::kana (leds)
KERNEL[1483.253496] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::kana (leds)
UDEV  [1483.255087] change   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::numlock (leds)
UDEV  [1483.255118] change   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::capslock (leds)
UDEV  [1483.255140] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::compose (leds)
UDEV  [1483.255239] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::capslock (leds)
UDEV  [1483.255280] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::numlock (leds)
UDEV  [1483.255632] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::scrolllock (leds)
UDEV  [1483.255925] change   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::kana (leds)
UDEV  [1483.256044] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35/input35::kana (leds)
KERNEL[1483.266653] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35 (input)
KERNEL[1483.266702] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/hidraw/hidraw3 (hidraw)
KERNEL[1483.266767] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013 (hid)
UDEV  [1483.267321] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/input/input35 (input)
KERNEL[1483.267636] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36/event9 (input)
UDEV  [1483.267832] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013/hidraw/hidraw3 (hidraw)
UDEV  [1483.267977] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36/event9 (input)
UDEV  [1483.268069] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.0/0003:28DE:1102.0013 (hid)
KERNEL[1483.280033] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36/mouse0 (input)
UDEV  [1483.280543] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36/mouse0 (input)
KERNEL[1483.289980] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36 (input)
KERNEL[1483.290010] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/hidraw/hidraw4 (hidraw)
KERNEL[1483.290037] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014 (hid)
KERNEL[1483.290245] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2/usbmisc/hiddev1 (usbmisc)
KERNEL[1483.293347] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2/0003:28DE:1102.0015/hidraw/hidraw5 (hidraw)
KERNEL[1483.293384] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2/0003:28DE:1102.0015 (hid)
UDEV  [1483.297047] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/input/input36 (input)
UDEV  [1483.297362] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014/hidraw/hidraw4 (hidraw)
UDEV  [1483.297641] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2/usbmisc/hiddev1 (usbmisc)
UDEV  [1483.297929] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2/0003:28DE:1102.0015/hidraw/hidraw5 (hidraw)
UDEV  [1483.298255] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.2/0003:28DE:1102.0015 (hid)
UDEV  [1483.298332] remove   /devices/pci0000:00/0000:00:04.0/usb3/3-1/3-1:1.1/0003:28DE:1102.0014 (hid)
KERNEL[1483.336761] remove   /devices/virtual/input/input37/event16 (input)
UDEV  [1483.337423] remove   /devices/virtual/input/input37/event16 (input)
KERNEL[1483.356822] remove   /devices/virtual/input/input37 (input)
UDEV  [1483.357815] remove   /devices/virtual/input/input37 (input)`

python output:
`Traceback (most recent call last):
  File "/usr/bin/sc-desktop.py", line 4, in <module>
    __import__('pkg_resources').run_script('python-steamcontroller==1.2', 'sc-desktop.py')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/python_steamcontroller-1.2-py3.6-linux-x86_64.egg/EGG-INFO/scripts/sc-desktop.py", line 104, in <module>
    _main()
  File "/usr/lib/python3.6/site-packages/python_steamcontroller-1.2-py3.6-linux-x86_64.egg/EGG-INFO/scripts/sc-desktop.py", line 99, in _main
    sc = SteamController(callback=evm.process)
  File "/usr/lib/python3.6/site-packages/python_steamcontroller-1.2-py3.6-linux-x86_64.egg/steamcontroller/__init__.py", line 176, in __init__
    raise ValueError('All SteamControler are busy')
ValueError: All SteamControler are busy
Exception ignored in: <bound method SteamController.__del__ of <steamcontroller.SteamController object at 0x7f17ac315f98>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/python_steamcontroller-1.2-py3.6-linux-x86_64.egg/steamcontroller/__init__.py", line 223, in __del__
    self._close()
  File "/usr/lib/python3.6/site-packages/python_steamcontroller-1.2-py3.6-linux-x86_64.egg/steamcontroller/__init__.py", line 217, in _close
    self._handle.releaseInterface(self._number)
AttributeError: 'SteamController' object has no attribute '_number'
[mbp@mbp ~]$ sudo sc-xbox.py debug
Traceback (most recent call last):
  File "/usr/bin/sc-xbox.py", line 4, in <module>
    __import__('pkg_resources').run_script('python-steamcontroller==1.2', 'sc-xbox.py')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/python_steamcontroller-1.2-py3.6-linux-x86_64.egg/EGG-INFO/scripts/sc-xbox.py", line 104, in <module>
    _main()
  File "/usr/lib/python3.6/site-packages/python_steamcontroller-1.2-py3.6-linux-x86_64.egg/EGG-INFO/scripts/sc-xbox.py", line 98, in _main
    sc = SteamController(callback=evm.process)
  File "/usr/lib/python3.6/site-packages/python_steamcontroller-1.2-py3.6-linux-x86_64.egg/steamcontroller/__init__.py", line 176, in __init__
    raise ValueError('All SteamControler are busy')
ValueError: All SteamControler are busy
Exception ignored in: <bound method SteamController.__del__ of <steamcontroller.SteamController object at 0x7f45cc1e3860>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/python_steamcontroller-1.2-py3.6-linux-x86_64.egg/steamcontroller/__init__.py", line 223, in __del__
    self._close()
  File "/usr/lib/python3.6/site-packages/python_steamcontroller-1.2-py3.6-linux-x86_64.egg/steamcontroller/__init__.py", line 217, in _close
    self._handle.releaseInterface(self._number)
AttributeError: 'SteamController' object has no attribute '_number'
`

**Comment by Christopher-P** [comment]
@Kokokokoka 
Removing the wired connection and using the wireless dongle fixed the **ValueError: All SteamControler are busy** issue for me and it started working as intended.

**Comment by Kokokokoka** [comment]
I've tried those scripts once again on a devuan system and found out that if one starts them from X server they're not working. If i close the X server, then start the script, then startx everything works. Still wired mode doesn't seem to be working and sc-mixed (it's a mix of joystick and mouse right?) doesn't seem to be working as a mouse. Wired mode spams with acpid events.
