### ISSUE TITLE
Missing dependency when running sc-xbox.py start and sc-desktop.py start: psutil

### ISSUE THREAD

**Issue by theMusicalGamer** [ynsta/steamcontroller#50]
When running the commands stated in the readme file, I got the error below:
```
pi@raspberrypi:~/Documents/GitHub/steamcontroller $ sudo sc-desktop.py start
Traceback (most recent call last):
  File "/usr/local/bin/sc-desktop.py", line 4, in <module>
    __import__('pkg_resources').run_script('python-steamcontroller==1.2', 'sc-desktop.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: psutil
```
Is there any reason that this is happening? I followed all of the instructions to the letter in the readme and am running Noobs 2.1.0 on a Raspberry Pi 3 Model B with Python 2.7.9.

**Comment by theMusicalGamer** [comment]
Updated and Upgraded; it's fixed
