### ISSUE TITLE
pkg_resources.DistributionNotFound: psutil, when trying to use sc-desktop.py start or sc-xbox.py start

### ISSUE THREAD

**Issue by Pesuri** [ynsta/steamcontroller#66]
It seems that I have the same problem as skeetcha had before (https://github.com/ynsta/steamcontroller/issues/50). I just set up Raspberry pi 3 today and tried to make steam controller to work with it.

When I try to run "sc-desktop.py start" or "sc-xbox.py start", I also get the same error message: 
"Traceback (most recent call last):
  File "/usr/local/bin/sc-desktop.py", line 4, in <module>
    __import__('pkg_resources').run_script('python-steamcontroller==1.2', 'sc-desktop.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: psutil"

I have tried to update and upgrade with terminal (sudo apt-get update and sudo apt-get upgrade) and I have rebooted raspberry few times, but it didn't help. When I tried to install psutil, I get a message that it has been already installed.

Any idea what might be wrong?

**Comment by malocscdth** [comment]
I have the same problem but i have see a difference enter this video: https://youtu.be/9eDsiZrhfSE at 4:04
at the last line : Finished processing dependancies for python-steamcontroller==1,0, me i have a error at this line.
